const BOOKS = [
  {
    id: 1,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    publicationYear: '1960',
    genre: '{"Fiction","Classic"}',
    description:
      'A classic novel depicting racial injustice in the American South.',
    coverImage: 'to-kill-a-mockingbird.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780210282386',
  },
  {
    id: 2,
    title: '1984',
    author: 'George Orwell',
    publicationYear: '1949',
    genre: '{"Dystopian","Science Fiction"}',
    description: 'A dystopian novel portraying a totalitarian society.',
    coverImage: '1984.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780680625180',
  },
  {
    id: 3,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    publicationYear: '1813',
    genre: '{"Classic","Romance"}',
    description:
      'A classic novel exploring themes of love, marriage, and social norms.',
    coverImage: 'pride-and-prejudice.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9782090180153',
  },
  {
    id: 4,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    publicationYear: '1925',
    genre: '{"Fiction","Classic"}',
    description:
      'A tale of the American Dream, wealth, and love during the Roaring Twenties.',
    coverImage: 'the-great-gatsby.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780330096067',
  },
  {
    id: 5,
    title: 'Moby-Dick',
    author: 'Herman Melville',
    publicationYear: '1851',
    genre: '{"Fiction","Adventure"}',
    description:
      'The epic tale of Captain Ahab obsession with the white whale.',
    coverImage: 'moby-dick.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780430746292',
  },
  {
    id: 6,
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    publicationYear: '1954',
    genre: '{"Fantasy","Adventure"}',
    description:
      'An epic fantasy saga about the quest to destroy the One Ring.',
    coverImage: 'the-loard-of-the-rings.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780080326525',
  },
  {
    id: 7,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    publicationYear: '1951',
    genre: '{"Fiction","Coming-of-age"}',
    description:
      'A classic coming-of-age novel following Holden Caulfield journey.',
    coverImage: 'the-catcher-in-the-rye.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780190159120',
  },
  {
    id: 8,
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    publicationYear: '1937',
    genre: '{"Fantasy","Adventure"}',
    description:
      'The prequel to The Lord of the Rings, following Bilbo Baggins journey.',
    coverImage: 'the-hobbit.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780710623784',
  },
  {
    id: 9,
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel Garcia Marquez',
    publicationYear: '1967',
    genre: '{"Magical Realism","Literary Fiction"}',
    description:
      'A multi-generational saga of the Buendía family in the fictional town of Macondo.',
    coverImage: 'one-hundred-years-of-solitude.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780950463568',
  },
  {
    id: 10,
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    publicationYear: '1869',
    genre: '{"Historical Fiction","Epic"}',
    description:
      'A monumental work depicting the events of Russian society during the Napoleonic era.',
    coverImage: 'war-and-peace.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780340276959',
  },
  {
    id: 11,
    title: 'The Odyssey',
    author: 'Homer',
    publicationYear: '8th century BCE',
    genre: '{"Epic","Mythology"}',
    description:
      'An ancient Greek epic poem recounting Odysseus ten-year journey home after the Trojan War.',
    coverImage: 'the-odyssey.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780830518058',
  },
  {
    id: 12,
    title: 'The Divine Comedy',
    author: 'Dante Alighieri',
    publicationYear: '1320',
    genre: '{"Epic","Poetry"}',
    description:
      'An epic poem that follows the journey of the soul through Hell, Purgatory, and Heaven.',
    coverImage: 'the-divine-comedy.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780480159726',
  },
  {
    id: 13,
    title: 'The Brothers Karamazov',
    author: 'Fyodor Dostoevsky',
    publicationYear: '1880',
    genre: '{"Classic","Philosophical Fiction"}',
    description:
      'A complex novel exploring themes of spirituality, morality, and human nature.',
    coverImage: 'the-brothers-karamazov.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780230505632',
  },
  {
    id: 14,
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    publicationYear: '1866',
    genre: '{"Classic","Psychological Fiction"}',
    description:
      'A psychological thriller revolving around guilt, conscience, and redemption.',
    coverImage: 'crime-and-punishment.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780560227151',
  },
  {
    id: 15,
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    publicationYear: '1890',
    genre: '{"Gothic","Philosophical Fiction"}',
    description:
      'A novel about a man whose portrait ages while he retains his youth and beauty.',
    coverImage: 'the-picture-of-dorian-gray.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780730175803',
  },
  {
    id: 16,
    title: 'Brave New World',
    author: 'Aldous Huxley',
    publicationYear: '1932',
    genre: '{"Dystopian","Science Fiction"}',
    description:
      'A dystopian vision of a future society obsessed with pleasure and conformity.',
    coverImage: 'brave-new-world.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780900318251',
  },
  {
    id: 17,
    title: 'The Count of Monte Cristo',
    author: 'Alexandre Dumas',
    publicationYear: '1844',
    genre: '{"Adventure","Historical Fiction"}',
    description:
      'An adventure novel of revenge, love, and redemption set in the early 19th century.',
    coverImage: 'the-count-of-monte-cristo.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780220871942',
  },
  {
    id: 18,
    title: 'Anna Karenina',
    author: 'Leo Tolstoy',
    publicationYear: '1877',
    genre: '{"Classic","Romance"}',
    description:
      'A tragic love story set against the backdrop of Russian high society.',
    coverImage: 'anna-karenina.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780780506978',
  },
  {
    id: 19,
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    publicationYear: '1988',
    genre: '{"Fiction","Philosophical"}',
    description:
      'A philosophical novel about a shepherd boy journey to find his personal legend.',
    coverImage: 'the-alchemist.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780920293687',
  },
  {
    id: 20,
    title: 'The Adventures of Huckleberry Finn',
    author: 'Mark Twain',
    publicationYear: '1884',
    genre: '{"Adventure","Satire"}',
    description:
      'A satirical novel following Huck Finn journey down the Mississippi River.',
    coverImage: 'the-advantures-of-huckleberry.png',
    quantity: Math.floor(Math.random() * 10) + 1,
    ISBNNo: '9780610261732',
  },
];

export default BOOKS;
